### ISSUE TITLE
`kill-connection-w/o-timer!` can take way too long

### ISSUE THREAD

**Issue by samth** [racket/web-server#71] opened 2019-09-13 15:27 UTC
When the `initial-connection-timeout` expires, the web server closes some ports and shuts down a custodian. However, this can take a surprisingly long time. In particular, the calls to `close-{input,output}-port` can add 500+ms of latency! It's not clear to me why this happens, but maybe there's something else we can do here.

To reproduce, see https://github.com/zkry/racket-test-server and note the spikes in the resulting picture. They correspond exactly to this timer, and if you change the initial timeout to 2, they happen every 2 seconds. If you comment out the two `with-handlers` forms in `kill-connection-w/o-timer!`, the spikes go away.

**Comment by samth** [comment] 2019-09-13 15:28
cc @zkry

**Comment by Bogdanp** [comment] 2019-09-13 17:12
I'm surprised the calls to `close-{input,output}-port` are necessary.  The documentation for `run-server` states that the connections are managed by a new custodian so shouldn't `custodian-shutdown-all` also close the ports in that case?

I tried connecting to the server via telnet, making a request and then waiting for the timeout.  When the lines are commented out, nothing happens and telnet hangs.  When they're left in, telnet receives the close packets.  

I don't know if this is related to why those calls take so long, but I figured it was worth mentioning.

**Comment by samth** [comment] 2019-09-13 17:59
As far as I can tell, `time` always reports 0 time for those calls, and the error handlers are never called in the benchmark. So I'm very confused.

**Comment by jeapostrophe** [comment] 2019-09-13 18:38
My guess is that you are observing the time to flush the buffers.

**Comment by samth** [comment] 2019-09-13 18:47
But which buffers are being flushed? And why does it impact other requests (which are presumably in other threads)?

**Comment by jeapostrophe** [comment] 2019-09-13 19:05
I assume it is the connection buffers? That could be why telnet hangs with them gone. There could be a blocking call somewhere in the kernel during closing as some special case?

**Comment by Bogdanp** [comment] 2019-09-14 06:54
I investigated a little further and I don't think the problem has to  do with buffering.  

The reason `telnet` hangs when I replace the body of `kill-connection-w/o-timer!` with `(void)` is because that makes it so that the input port is never closed. Because it is never closed,  the `connection-loop` inside `handle-connection/cm` never exits (because there's no input  coming in and because the `port-close-evt` on the input port never fires (because it is never closed)).  That makes sense, although I'm still surprised that the `connection-loop`-ing thread isn't killed when the custodian gets shut down.

However, when the unmodified `kill-connection-w/o-timer!` is triggered, it closes the two ports and then shuts down the custodian, which triggers the `port-close-evt` inside of `handle-connection/cm`, which is *running inside a thread belonging to the custodian being shut down*, which itself calls `kill-connection!` again, attempting to close the ports again and then shutting down the custodian again. The `connection-loop` then terminates and the connection handling function exits, which signals to `run-server` that the custodian should be shut down... again.

When I modify `kill-connection-w/o-timer!` so that all it does is close the input port, the spikes go away and the connection-closing after a timeout behavior is preserved, which leads me to think that the issue is actually calling `custodian-shutdown-all` from within a thread that is managed by the custodian that is being asked to shut down that is the problem. Either that or there's something else going on within `run-server`. I don't know enough about the runtime yet to know for sure, but does that sound plausible?

You can test this yourselves by changing `kill-connection-w/o-timer!` to:

```racket
(define (kill-connection-w/o-timer! conn)
  (with-handlers ([exn:fail:network? void])
    (close-input-port (connection-i-port conn))))
```

**Closed** 2019-10-28 20:11 UTC
